openapi: 3.0.3
info:
  title: Hjelpemiddelsøknad model spec
  version: 1.0.0
paths:
  /dummy:
    get:
      responses:
        '200':
          description: OK
          content: {}

components:
  schemas:

    Soknadsdata:
      type: object
      required:
        - bruker
        - formidler
        - hjelpemidler
        - hjelpemiddelTotalAntall
        - oppfolgingsansvarlig
        - levering
      properties:
        bruker:
          $ref: '#/components/schemas/Bruker'
        formidler:
          $ref: '#/components/schemas/Formidler'
        hjelpemidler:
          type: array
          items:
            $ref: '#/components/schemas/Hjelpemiddel'
        hjelpemiddelTotalAntall:
          type: integer
        oppfolgingsansvarlig:
          $ref: '#/components/schemas/Oppfolgingsansvarlig'
        levering:
          $ref: '#/components/schemas/Levering'

    Bruker:
      type: object
      required:
        - etternavn
        - fornavn
        - fnummer
        - telefonNummer
        - boform
        - bruksarena
        - funksjonsnedsettelser
        - signatur
      properties:
        etternavn:
          type: string
        fornavn:
          type: string
        fnummer:
          type: string
          minLength: 11
          maxLength: 11
        telefonNummer:
          type: string
        adresse:
          type: string
        postnummer:
          type: string
          minLength: 4
          maxLength: 4
        poststed:
          type: string
        boform:
          type: string
        bruksarena:
          $ref: '#/components/schemas/Bruksarena'
        funksjonsnedsettelser:
          type: array
          items:
            $ref: '#/components/schemas/Funksjonsnedsettelse'
        signatur:
            $ref: '#/components/schemas/SignaturType'
        kroppsmaal:
          $ref: '#/components/schemas/Kroppsmaal'

    Bruksarena:
      type: string
      enum:
        - DAGLIGLIVET
        - UKJENT
    
    Funksjonsnedsettelse:
      type: string
      enum:
        - BEVEGELSE
        - HORSEL
        - KOGNISJON
    
    SignaturType:
      type: string
      enum:
        - BRUKER_BEKREFTER
        - FULLMAKT
          
    Kroppsmaal:
      type: object
      properties:
        setebredde:
          type: integer
        laarlengde:
          type: integer
        legglengde:
          type: integer
        hoyde:
          type: integer
        kroppsvekt:
          type: integer

    Formidler:
      type: object
      required:
        - navn
        - arbeidssted
        - stilling
        - adresse
        - telefon
        - treffesEnklest
        - epost
      properties:
        navn:
          type: string
        arbeidssted:
          type: string
        stilling:
          type: string
        adresse:
          type: string
        telefon:
          type: string
        treffesEnklest:
          type: string
        epost:
          type: string
        kommunenavn:
          type: string

    Hjelpemiddel:
      type: object
      required:
        - antall
        - beskrivelse
        - hjelpemiddelkategori
        - hmsNr
        - andreKommentarer
        - utlevertFraHjelpemiddelsentralen
        - kanIkkeHaTilsvarande
      properties:
        navn:
          type: string
        antall:
          type: integer
        beskrivelse:
          type: string
        hjelpemiddelkategori:
          type: string
        hmsNr:
          type: string
        rangering:
          type: string
        andreKommentarer:
          type: string
        utlevertFraHjelpemiddelsentralen:
          type: boolean
        utlevertInfo:
          $ref: '#/components/schemas/UtlevertInfo'
        vilkarliste:
          type: array
          items:
            $ref: '#/components/schemas/HjelpemiddelVilkar'
        tilbehorListe:
          type: array
          items:
            $ref: '#/components/schemas/Tilbehor'
        kanIkkeHaTilsvarande:
          type: boolean
        begrunnelse:
          type: string
          description: Begrunnelse for hvorfor bruker ikke kan ha tilsvarende hjelpemiddel eller hjelpemiddel med høyere rangering.
        tilleggsinfo:
          type: array
          items:
            $ref: '#/components/schemas/Tilleggsinfo'
    
    UtlevertInfo:
      type: object
      properties:
        utlevertType:
          $ref: '#/components/schemas/UtlevertType'
        overfoertFraBruker: 
          type: string
        annenKommentar:
          type: string
    
    UtlevertType:
      type: string
      enum:
        - FREMSKUTT_LAGER
        - KORTTIDSLAAN
        - OVERFOERT
        - ANNET

    HjelpemiddelVilkar:
      type: object
      required:
        - vilkaarTekst
      properties:
        vilkaarTekst:
          type: string
        tilleggsInfo:
          type: string

    Tilbehor:
      type: object
      required:
        - hmsnr
        - navn
      properties:
        hmsnr:
          type: string
        antall:
          type: integer
        navn:
          type: string

    Tilleggsinfo:
      type: object
      required:
        - key
      properties:
        key: 
          type: string
          enum:
            - RULLESTOL_SKAL_BRUKES_I_BIL
            - SITTEPUTEVALG_STANDARD_SITTEPUTE
            - SITTEPUTEVALG_LEGGES_TIL_SEPARAT
            - SITTEPUTEVALG_HAR_FRA_FOR
            - SITTEPUTEVALG_TRENGER_SITTEPUTE

    Oppfolgingsansvarlig:
      type: object
      required:
        - navn
        - arbeidssted
        - stilling
        - telefon
        - ansvarFor
      properties:
        navn:
          type: string
        arbeidssted:
          type: string
        stilling:
          type: string
        telefon:
          type: string
        ansvarFor:
          type: string

    Levering:
      type: object
      required:
        - kontaktPerson
        - leveringsmaate
      properties:
        kontaktPerson:
          $ref: '#/components/schemas/KontaktPerson'
        leveringsmaate:
          $ref: '#/components/schemas/Leveringsmaate'
        adresse:
          type: string
        merknad:
          type: string
    
    KontaktPerson:
      type: object
      required:
        - kontaktpersonType
      properties:
        navn:
          type: string
        telefon:
          type: string
        kontaktpersonType:
          $ref: '#/components/schemas/KontaktpersonType'

    KontaktpersonType:
      type: string
      enum:
        - HJELPEMIDDELBRUKER
        - HJELPEMIDDELFORMIDLER
        - ANNEN_KONTAKTPERSON
        - INGEN_KONTAKTPERSON
    
    Leveringsmaate:
      type: string
      enum:
        - FOLKEREGISTRERT_ADRESSE
        - ANNEN_ADRESSE
        - HJELPEMIDDELSENTRAL
        - ALLEREDE_LEVERT
