openapi: 3.0.3
info:
  title: Hjelpemiddelsøknad model spec
  version: 1.0.0
paths:
  /dummy:
    get:
      responses:
        '200':
          description: OK
          content: {}
components:
  schemas:
    Bruker:
      type: object
      required:
        - etternavn
        - fornavn
        - fnummer
        - telefonNummer
        - boform
        - bruksarena
        - funksjonsnedsettelser
        - signatur
      properties:
        etternavn:
          type: string
        fornavn:
          type: string
        fnummer:
          type: string
          minLength: 11
          maxLength: 11
        telefonNummer:
          type: string
          minLength: 8
          maxLength: 8
        adresse:
          type: string
        postnummer:
          type: string
          minLength: 4
          maxLength: 4
        poststed:
          type: string
        boform:
          type: string
          enum:
            - Hjemme
            - Institusjon
        bruksarena:
          type: string
          enum:
            - Dagligliv
            - Ukjent
        funksjonsnedsettelser:
          type: array
          items:
            type: string
            enum:
              - Bevegelse
              - Hørsel
              - Kognisjon
        signatur:
          type: string
          enum:
            - Fullmakt
            - Brukerbekreftelse
        kroppsmaal:
          $ref: "#/components/schemas/Kroppsmaal"
          
    Kroppsmaal:
      type: object
      properties:
        setebredde:
          type: integer
        laarlengde:
          type: integer
        legglengde:
          type: integer
        hoyde:
          type: integer
        kroppsvekt:
          type: integer

    Formidler:
      type: object
      required:
        - navn
        - arbeidssted
        - stilling
        - adresse
        - telefon
        - treffesEnklest
        - epost
      properties:
        navn:
          type: string
        arbeidssted:
          type: string
        stilling:
          type: string
        adresse:
          type: string
        telefon:
          type: string
          minLength: 8
          maxLength: 8
        treffesEnklest:
          type: string
        epost:
          type: string
        kommunenavn:
          type: string
    Hjelpemiddel:
      type: object
      required:
        - antall
        - beskrivelse
        - hmsNr
        - tilleggsinformasjon
        - utlevertFraHjelpemiddelsentralen
        - kanIkkeTilsvarende
      properties:
        antall:
          type: integer
        beskrivelse:
          type: string
        hjelpemiddelkategori:
          type: string
        hmsNr:
          type: string
        tilleggsinformasjon:
          type: string
        rangering:
          type: string
        utlevertFraHjelpemiddelsentralen:
          type: boolean
        vilkarliste:
          type: array
          items:
            $ref: '#/components/schemas/HjelpemiddelVilkar'
        tilbehorListe:
          type: array
          items:
            $ref: '#/components/schemas/Tilbehor'
        begrunnelse:
          type: string
        kanIkkeTilsvarande:
          type: boolean
        navn:
          type: string
        rullestolInfo:
          type: object
          properties:
            skalBrukesIBil:
              type: boolean
    HjelpemiddelVilkar:
      type: object
      required:
        - vilkaarTekst
      properties:
        vilkaarTekst:
          type: string
        tilleggsInfo:
          type: string
    Tilbehor:
      type: object
      required:
        - hmsnr
        - antall
        - navn
      properties:
        hmsnr:
          type: string
        antall:
          type: integer
          minimum: 1
        navn:
          type: string
    Oppfolgingsansvarlig:
      type: object
      required:
        - navn
        - arbeidssted
        - stilling
        - telefon
        - ansvarFor
      properties:
        navn:
          type: string
        arbeidssted:
          type: string
        stilling:
          type: string
        telefon:
          type: string
          minLength: 8
          maxLength: 8
        ansvarFor:
          type: string
    Levering:
      type: object
      required:
        - kontaktPerson
        - leveringsmaate
      properties:
        kontaktPerson:
          $ref: '#/components/schemas/KontaktPerson'
        leveringsmaate:
          type: string
          enum:
            - FOLKEREGISTRERT_ADRESSE
            - ANNEN_ADRESSE
            - HJELPEMIDDELSENTRAL
            - ALLEREDE_LEVERT
        adresse:
          type: string
        merknad:
          type: string
    KontaktPerson:
      type: object
      required:
        - kontaktpersonType
      properties:
        navn:
          type: string
        telefon:
          type: string
          minLength: 8
          maxLength: 8
        kontaktpersonType:
          type: string
          enum:
            - HJELPEMIDDELBRUKER
            - HJELPEMIDDELFORMIDLER
            - ANNEN_KONTAKTPERSON
            - INGEN_KONTAKTPERSON
    Soknadsdata:
      type: object
      required:
        - bruker
        - formidler
        - hjelpemidler
        - hjelpemiddelTotalAntall
        - oppfolgingsansvarlig
        - levering
      properties:
        bruker:
          $ref: '#/components/schemas/Bruker'
        formidler:
          $ref: '#/components/schemas/Formidler'
        hjelpemidler:
          type: array
          items:
            $ref: '#/components/schemas/Hjelpemiddel'
        hjelpemiddelTotalAntall:
          type: integer
        oppfolgingsansvarlig:
          $ref: '#/components/schemas/Oppfolgingsansvarlig'
        levering:
          $ref: '#/components/schemas/Levering'
