/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Bruksarena } from './bruksarena';
import { Funksjonsnedsettelse } from './funksjonsnedsettelse';
import { Kroppsmaal } from './kroppsmaal';
import { SignaturType } from './signaturType';

export class Bruker {
    'etternavn': string;
    'fornavn': string;
    'fnummer': string;
    'telefonNummer': string;
    'adresse'?: string;
    'postnummer'?: string;
    'poststed'?: string;
    'boform': string;
    'bruksarena': Bruksarena;
    'funksjonsnedsettelser': Array<Funksjonsnedsettelse>;
    'signatur': SignaturType;
    'kroppsmaal'?: Kroppsmaal;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "etternavn",
            "baseName": "etternavn",
            "type": "string"
        },
        {
            "name": "fornavn",
            "baseName": "fornavn",
            "type": "string"
        },
        {
            "name": "fnummer",
            "baseName": "fnummer",
            "type": "string"
        },
        {
            "name": "telefonNummer",
            "baseName": "telefonNummer",
            "type": "string"
        },
        {
            "name": "adresse",
            "baseName": "adresse",
            "type": "string"
        },
        {
            "name": "postnummer",
            "baseName": "postnummer",
            "type": "string"
        },
        {
            "name": "poststed",
            "baseName": "poststed",
            "type": "string"
        },
        {
            "name": "boform",
            "baseName": "boform",
            "type": "string"
        },
        {
            "name": "bruksarena",
            "baseName": "bruksarena",
            "type": "Bruksarena"
        },
        {
            "name": "funksjonsnedsettelser",
            "baseName": "funksjonsnedsettelser",
            "type": "Array<Funksjonsnedsettelse>"
        },
        {
            "name": "signatur",
            "baseName": "signatur",
            "type": "SignaturType"
        },
        {
            "name": "kroppsmaal",
            "baseName": "kroppsmaal",
            "type": "Kroppsmaal"
        }    ];

    static getAttributeTypeMap() {
        return Bruker.attributeTypeMap;
    }
}

