/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HjelpemiddelVilkar } from './hjelpemiddelVilkar';
import { RullestolInfo } from './rullestolInfo';
import { Tilbehor } from './tilbehor';

export class Hjelpemiddel {
    'antall': number;
    'beskrivelse': string;
    'hjelpemiddelkategori': string;
    'hmsNr': string;
    'tilleggsinformasjon': string;
    'rangering'?: string;
    'utlevertFraHjelpemiddelsentralen': boolean;
    'vilkarliste'?: Array<HjelpemiddelVilkar>;
    'tilbehorListe'?: Array<Tilbehor>;
    'begrunnelse'?: string;
    'kanIkkeTilsvarande'?: boolean;
    'navn'?: string;
    'rullestolInfo'?: RullestolInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "antall",
            "baseName": "antall",
            "type": "number"
        },
        {
            "name": "beskrivelse",
            "baseName": "beskrivelse",
            "type": "string"
        },
        {
            "name": "hjelpemiddelkategori",
            "baseName": "hjelpemiddelkategori",
            "type": "string"
        },
        {
            "name": "hmsNr",
            "baseName": "hmsNr",
            "type": "string"
        },
        {
            "name": "tilleggsinformasjon",
            "baseName": "tilleggsinformasjon",
            "type": "string"
        },
        {
            "name": "rangering",
            "baseName": "rangering",
            "type": "string"
        },
        {
            "name": "utlevertFraHjelpemiddelsentralen",
            "baseName": "utlevertFraHjelpemiddelsentralen",
            "type": "boolean"
        },
        {
            "name": "vilkarliste",
            "baseName": "vilkarliste",
            "type": "Array<HjelpemiddelVilkar>"
        },
        {
            "name": "tilbehorListe",
            "baseName": "tilbehorListe",
            "type": "Array<Tilbehor>"
        },
        {
            "name": "begrunnelse",
            "baseName": "begrunnelse",
            "type": "string"
        },
        {
            "name": "kanIkkeTilsvarande",
            "baseName": "kanIkkeTilsvarande",
            "type": "boolean"
        },
        {
            "name": "navn",
            "baseName": "navn",
            "type": "string"
        },
        {
            "name": "rullestolInfo",
            "baseName": "rullestolInfo",
            "type": "RullestolInfo"
        }    ];

    static getAttributeTypeMap() {
        return Hjelpemiddel.attributeTypeMap;
    }
}

