/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum KontaktpersonType {
    HJELPEMIDDELBRUKER = <any> 'HJELPEMIDDELBRUKER',
    HJELPEMIDDELFORMIDLER = <any> 'HJELPEMIDDELFORMIDLER',
    ANNEN_KONTAKTPERSON = <any> 'ANNEN_KONTAKTPERSON',
    INGEN_KONTAKTPERSON = <any> 'INGEN_KONTAKTPERSON'
}
