/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { KontaktpersonType } from './kontaktpersonType';

export class KontaktPerson {
    'navn'?: string;
    'telefon'?: string;
    'kontaktpersonType': KontaktpersonType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "navn",
            "baseName": "navn",
            "type": "string"
        },
        {
            "name": "telefon",
            "baseName": "telefon",
            "type": "string"
        },
        {
            "name": "kontaktpersonType",
            "baseName": "kontaktpersonType",
            "type": "KontaktpersonType"
        }    ];

    static getAttributeTypeMap() {
        return KontaktPerson.attributeTypeMap;
    }
}

