/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Kroppsmaal {
    'setebredde'?: number;
    'laarlengde'?: number;
    'legglengde'?: number;
    'hoyde'?: number;
    'kroppsvekt'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "setebredde",
            "baseName": "setebredde",
            "type": "number"
        },
        {
            "name": "laarlengde",
            "baseName": "laarlengde",
            "type": "number"
        },
        {
            "name": "legglengde",
            "baseName": "legglengde",
            "type": "number"
        },
        {
            "name": "hoyde",
            "baseName": "hoyde",
            "type": "number"
        },
        {
            "name": "kroppsvekt",
            "baseName": "kroppsvekt",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Kroppsmaal.attributeTypeMap;
    }
}

