/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Oppfolgingsansvarlig {
    'navn': string;
    'arbeidssted': string;
    'stilling': string;
    'telefon': string;
    'ansvarFor': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "navn",
            "baseName": "navn",
            "type": "string"
        },
        {
            "name": "arbeidssted",
            "baseName": "arbeidssted",
            "type": "string"
        },
        {
            "name": "stilling",
            "baseName": "stilling",
            "type": "string"
        },
        {
            "name": "telefon",
            "baseName": "telefon",
            "type": "string"
        },
        {
            "name": "ansvarFor",
            "baseName": "ansvarFor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Oppfolgingsansvarlig.attributeTypeMap;
    }
}

