/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum SignaturType {
    BRUKER_BEKREFTER = <any> 'BRUKER_BEKREFTER',
    FULLMAKT = <any> 'FULLMAKT',
    FRITAK_FRA_FULLMAKT = <any> 'FRITAK_FRA_FULLMAKT'
}
