/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Bruker } from './bruker';
import { Formidler } from './formidler';
import { Hjelpemiddel } from './hjelpemiddel';
import { Levering } from './levering';
import { Oppfolgingsansvarlig } from './oppfolgingsansvarlig';

export class Soknadsdata {
    'bruker': Bruker;
    'formidler': Formidler;
    'hjelpemidler': Array<Hjelpemiddel>;
    'hjelpemiddelTotalAntall': number;
    'oppfolgingsansvarlig'?: Oppfolgingsansvarlig;
    'levering': Levering;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bruker",
            "baseName": "bruker",
            "type": "Bruker"
        },
        {
            "name": "formidler",
            "baseName": "formidler",
            "type": "Formidler"
        },
        {
            "name": "hjelpemidler",
            "baseName": "hjelpemidler",
            "type": "Array<Hjelpemiddel>"
        },
        {
            "name": "hjelpemiddelTotalAntall",
            "baseName": "hjelpemiddelTotalAntall",
            "type": "number"
        },
        {
            "name": "oppfolgingsansvarlig",
            "baseName": "oppfolgingsansvarlig",
            "type": "Oppfolgingsansvarlig"
        },
        {
            "name": "levering",
            "baseName": "levering",
            "type": "Levering"
        }    ];

    static getAttributeTypeMap() {
        return Soknadsdata.attributeTypeMap;
    }
}

