/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Tilleggsinfo {
    'key': Tilleggsinfo.KeyEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "Tilleggsinfo.KeyEnum"
        }    ];

    static getAttributeTypeMap() {
        return Tilleggsinfo.attributeTypeMap;
    }
}

export namespace Tilleggsinfo {
    export enum KeyEnum {
        RULLESTOL_SKAL_BRUKES_I_BIL = <any> 'RULLESTOL_SKAL_BRUKES_I_BIL',
        SITTEPUTEVALG_STANDARD_SITTEPUTE = <any> 'SITTEPUTEVALG_STANDARD_SITTEPUTE',
        SITTEPUTEVALG_LEGGES_TIL_SEPARAT = <any> 'SITTEPUTEVALG_LEGGES_TIL_SEPARAT',
        SITTEPUTEVALG_HAR_FRA_FOR = <any> 'SITTEPUTEVALG_HAR_FRA_FOR',
        SITTEPUTEVALG_TRENGER_SITTEPUTE = <any> 'SITTEPUTEVALG_TRENGER_SITTEPUTE'
    }
}
