/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Tilleggsinfo {
    'key': Tilleggsinfo.KeyEnum;
    /**
    * JSON med eventuelle verdier f.eks. begrunnelse for KAN_IKKE_HA_TILSVARENDE_BEGRUNNELSE.
    */
    'values'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "Tilleggsinfo.KeyEnum"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Tilleggsinfo.attributeTypeMap;
    }
}

export namespace Tilleggsinfo {
    export enum KeyEnum {
        RULLESTOL_SKAL_BRUKES_I_BIL = <any> 'RULLESTOL_SKAL_BRUKES_I_BIL',
        SITTEPUTEVALG_STANDARD_SITTEPUTE = <any> 'SITTEPUTEVALG_STANDARD_SITTEPUTE',
        SITTEPUTEVALG_LEGGES_TIL_SEPARAT = <any> 'SITTEPUTEVALG_LEGGES_TIL_SEPARAT',
        SITTEPUTEVALG_HAR_FRA_FOR = <any> 'SITTEPUTEVALG_HAR_FRA_FOR',
        SITTEPUTEVALG_TRENGER_SITTEPUTE = <any> 'SITTEPUTEVALG_TRENGER_SITTEPUTE',
        LAVERE_RANGERING_BEGRUNNELSE = <any> 'LAVERE_RANGERING_BEGRUNNELSE',
        KAN_IKKE_HA_TILSVARENDE_BEGRUNNELSE = <any> 'KAN_IKKE_HA_TILSVARENDE_BEGRUNNELSE',
        PERSONLOFTER_VALG_HAR_BEHOV_FOR_SEIL_ELLER_SELE = <any> 'PERSONLOFTER_VALG_HAR_BEHOV_FOR_SEIL_ELLER_SELE',
        ANNEN_KOMMENTAR = <any> 'ANNEN_KOMMENTAR'
    }
}
