/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum UtlevertType {
    FremskuttLager = <any> 'FremskuttLager',
    Korttidsln = <any> 'Korttidslån',
    Overfrt = <any> 'Overført',
    Annet = <any> 'Annet'
}
