/**
* Hjelpemiddel søknad model spec
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.nav.hjelpemidler.domain.models


import com.squareup.moshi.Json

/**
 * 
 * @param kontaktpersonType 
 * @param navn 
 * @param telefon 
 */

data class KontaktPerson (
    @Json(name = "kontaktpersonType")
    val kontaktpersonType: KontaktPerson.KontaktpersonType,
    @Json(name = "navn")
    val navn: kotlin.String? = null,
    @Json(name = "telefon")
    val telefon: kotlin.String? = null
) {

    /**
     * 
     * Values: HJELPEMIDDELBRUKER,HJELPEMIDDELFORMIDLER,ANNEN_KONTAKTPERSON,INGEN_KONTAKTPERSON
     */
    enum class KontaktpersonType(val value: kotlin.String) {
        @Json(name = "HJELPEMIDDELBRUKER") HJELPEMIDDELBRUKER("HJELPEMIDDELBRUKER"),
        @Json(name = "HJELPEMIDDELFORMIDLER") HJELPEMIDDELFORMIDLER("HJELPEMIDDELFORMIDLER"),
        @Json(name = "ANNEN_KONTAKTPERSON") ANNEN_KONTAKTPERSON("ANNEN_KONTAKTPERSON"),
        @Json(name = "INGEN_KONTAKTPERSON") INGEN_KONTAKTPERSON("INGEN_KONTAKTPERSON");
    }
}

