/**
* Hjelpemiddelsøknad model spec
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.nav.hjelpemidler.domain.models

import no.nav.hjelpemidler.domain.models.Bruksarena
import no.nav.hjelpemidler.domain.models.Funksjonsnedsettelse
import no.nav.hjelpemidler.domain.models.Kroppsmaal
import no.nav.hjelpemidler.domain.models.SignaturType

import com.squareup.moshi.Json

/**
 * 
 * @param etternavn 
 * @param fornavn 
 * @param fnummer 
 * @param telefonNummer 
 * @param boform 
 * @param bruksarena 
 * @param funksjonsnedsettelser 
 * @param signatur 
 * @param adresse 
 * @param postnummer 
 * @param poststed 
 * @param kroppsmaal 
 */

data class Bruker (
    @Json(name = "etternavn")
    val etternavn: kotlin.String,
    @Json(name = "fornavn")
    val fornavn: kotlin.String,
    @Json(name = "fnummer")
    val fnummer: kotlin.String,
    @Json(name = "telefonNummer")
    val telefonNummer: kotlin.String,
    @Json(name = "boform")
    val boform: kotlin.String,
    @Json(name = "bruksarena")
    val bruksarena: Bruksarena,
    @Json(name = "funksjonsnedsettelser")
    val funksjonsnedsettelser: kotlin.collections.List<Funksjonsnedsettelse>,
    @Json(name = "signatur")
    val signatur: SignaturType,
    @Json(name = "adresse")
    val adresse: kotlin.String? = null,
    @Json(name = "postnummer")
    val postnummer: kotlin.String? = null,
    @Json(name = "poststed")
    val poststed: kotlin.String? = null,
    @Json(name = "kroppsmaal")
    val kroppsmaal: Kroppsmaal? = null
)

