/**
* Hjelpemiddelsøknad model spec
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.nav.hjelpemidler.domain.models


import com.squareup.moshi.Json

/**
 * 
 * @param bevegelse 
 * @param kognisjon 
 * @param horsel 
 */

data class BrukerFunksjonsnedsettelser (
    @Json(name = "bevegelse")
    val bevegelse: kotlin.Boolean? = null,
    @Json(name = "kognisjon")
    val kognisjon: kotlin.Boolean? = null,
    @Json(name = "horsel")
    val horsel: kotlin.Boolean? = null
)

