/**
* Hjelpemiddelsøknad model spec
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.nav.hjelpemidler.domain.models


import com.squareup.moshi.Json

/**
 * 
 * @param dummy2 used to trigger changes to model while debugging github actions
 */

data class Dummy (
    /* used to trigger changes to model while debugging github actions */
    @Json(name = "dummy2")
    val dummy2: kotlin.String? = null
)

