/**
* Hjelpemiddel søknad model spec
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.nav.hjelpemidler.domain.models


import com.squareup.moshi.Json

/**
 * 
 * @param vilkaarTekst 
 * @param tilleggsInfo 
 */

data class HjelpemiddelVilkar (
    @Json(name = "vilkaarTekst")
    val vilkaarTekst: kotlin.String,
    @Json(name = "tilleggsInfo")
    val tilleggsInfo: kotlin.String? = null
)

