/**
* Hjelpemiddelsøknad model spec
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.nav.hjelpemidler.domain.models

import no.nav.hjelpemidler.domain.models.Bruker
import no.nav.hjelpemidler.domain.models.Formidler
import no.nav.hjelpemidler.domain.models.Hjelpemiddel
import no.nav.hjelpemidler.domain.models.Levering
import no.nav.hjelpemidler.domain.models.Oppfolgingsansvarlig

import com.squareup.moshi.Json

/**
 * 
 * @param bruker 
 * @param formidler 
 * @param hjelpemidler 
 * @param hjelpemiddelTotalAntall 
 * @param oppfolgingsansvarlig 
 * @param levering 
 */

data class Soknadsdata (
    @Json(name = "bruker")
    val bruker: Bruker,
    @Json(name = "formidler")
    val formidler: Formidler,
    @Json(name = "hjelpemidler")
    val hjelpemidler: kotlin.collections.List<Hjelpemiddel>,
    @Json(name = "hjelpemiddelTotalAntall")
    val hjelpemiddelTotalAntall: kotlin.Int,
    @Json(name = "oppfolgingsansvarlig")
    val oppfolgingsansvarlig: Oppfolgingsansvarlig,
    @Json(name = "levering")
    val levering: Levering
)

