/**
* Hjelpemiddelsøknad model spec
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package no.nav.hjelpemidler.domain.models

import no.nav.hjelpemidler.domain.models.UtlevertType

import com.squareup.moshi.Json

/**
 * 
 * @param utlevertType 
 * @param overfRtFraBruker 
 * @param annenKommentar 
 */

data class UtlevertInfo (
    @Json(name = "utlevertType")
    val utlevertType: UtlevertType? = null,
    @Json(name = "overførtFraBruker")
    val overfRtFraBruker: kotlin.String? = null,
    @Json(name = "annenKommentar")
    val annenKommentar: kotlin.String? = null
)

