graph TD

    formidler((Formidler)) -. GUI: Fyller inn søknad .-> hmsoknad    

    hmsoknad[hm-soknad] -- REST: Søknad JSON --> soknad_api[hm-soknad-api]
    soknad_api -- NySøknadMedFullmakt --> sokbeh_med_fullmkt[hm-soknadsbehandling]
    soknad_api -- NySøknadUtenFullmakt --> sokbeh_uten_fullmkt[hm-soknadsbehandling]

    sokbeh_uten_fullmkt -- SøknadTilGodkjenning --> brukerbek_venter_godkj[hm-dinehjelpemidler]
    brukerbek_venter_godkj -. Oppgave .-> dittnav_brukerbekreftelse>DittNAV]
    dittnav_brukerbekreftelse -. SMS/epost: ny oppgave .-> bruker
    bruker((Bruker)) -. GUI: Bekrefter/Sletter søknad .-> brukerbek_bruker_svar[hm-dinehjelpemidler]
    brukerbek_bruker_svar -- GodkjennSøknad --> sokbeh_godkjent[hm-soknadsbehandling]
    
    brukerbek_bruker_svar -- SlettSøknad --> sokbeh_slettet[hm-soknadsbehandling]
    hmsokbeh_utløpt[hm-soknadsbehandling] -- hm-GodkjenningsfristErUtløpt --> brukerbek_done[hm-dinehjelpemidler]
    sokbeh_slettet -- SøknadSlettetAvBruker --> brukerbek_done
    brukerbek_done -. Done .-> dittnav_done>DittNAV]

    sokbeh_godkjent -- hm-SøknadGodkjentAvBruker --> brukerbek_done
    sokbeh_godkjent -- hm-SøknadGodkjentAvBruker --> joarksink[hm-joark-sink]
    sokbeh_med_fullmkt -- hm-Søknad --> joarksink
    
    joarksink -.-> joark>JOARK]
    joarksink -- hm-SøknadArkivert --> sokbeh1[hm-soknadsbehandling]
    joarksink -- hm-SøknadArkivert --> oppgavesink[hm-oppgave-sink]

    oppgavesink -.-> oebs>OEBS]
    oppgavesink -- hm-OppgaveOpprettet --> sokbeh1
    oppgavesink -- OppgaveOpprettet --> hmbrukerbekreftelse_oppg_opprettet[hm-dinehjelpemidler]
    hmbrukerbekreftelse_oppg_opprettet -. Beskjed .-> dittnav_oppg_opprettet>DittNAV]
