name: Generate updated models from openapi.yaml

on:
  push:
    branches:
      - main
    paths:
      - openapi.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Generate datamodels
        run: |
          chmod u+x generer-datamodeller.sh
          ./generer-datamodeller.sh
      # - name: Build package
      #   run: |
      #     cd hm-datamodell-kotlin
      #     chmod u+x gradlew
      #     ./gradlew build
      # - name: Publish package
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     cd hm-datamodell-kotlin
      #     ./gradlew publish
      - name: Commit and push generated files
        run: |
          git config --global user.name hm-docs-bot
          git config --global user.email hm-docs-bot@users.noreply.github.com
          git add hm-datamodell-kotlin/docs
          git add hm-datamodell-kotlin/src
          git commit -m "Update generated models"
          git push