name: Generate updated models from openapi.yaml for Kotlin and TypeScript, and create release

on:
  push:
    branches:
      - main
    paths:
      - openapi.yaml
      - generer-datamodeller.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Generate datamodels
        run: |
          chmod u+x generer-datamodeller.sh
          ./generer-datamodeller.sh
      - name: Pre-deploy
        uses: navikt/digihot-deploy/actions/pre-deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push generated files
        run: |
          git config --global user.name hm-docs-bot
          git config --global user.email hm-docs-bot@users.noreply.github.com
          
          git add hm-datamodell-kotlin/docs
          git add hm-datamodell-kotlin/src
          git add hm-datamodell-typescript/model

          cd hm-datamodell-typescript
          npm --no-git-tag-version version ${{ env.VERSION_TAG }}
          npm install
          git add package.json
          git add package-lock.json

          git commit -m "Update generated models"
          git push
      - name: Post-deploy
        uses: navikt/digihot-deploy/actions/post-deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: ${{ env.APPLICATION }} ${{ env.VERSION_TAG }}
          body: ${{ env.CHANGE_LOG }}
          draft: true
          prerelease: false