name: Publish hm-datamodell-typescript to npmjs
on:
  release:
    types: [published]

jobs:
  deploy-prod:
    name: Publish TypeScript models to npmjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish hm-datamodell-typescript to npmjs
        run: |
          cd hm-datamodell-typescript
          npm install
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}