/* tslint:disable */
/* eslint-disable */
/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bruker
 */
export interface Bruker {
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    etternavn: string;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    fornavn: string;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    fnummer: string;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    telefonNummer: string;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    adresse?: string;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    postnummer?: string;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    poststed?: string;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    boform: BrukerBoformEnum;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    bruksarena: BrukerBruksarenaEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Bruker
     */
    funksjonsnedsettelser: Array<BrukerFunksjonsnedsettelserEnum>;
    /**
     * 
     * @type {string}
     * @memberof Bruker
     */
    signatur: BrukerSignaturEnum;
}

/**
* @export
* @enum {string}
*/
export enum BrukerBoformEnum {
    HJEMME = 'Hjemme',
    INSTITUSJON = 'Institusjon'
}/**
* @export
* @enum {string}
*/
export enum BrukerBruksarenaEnum {
    DAGLIGLIV = 'Dagligliv',
    UKJENT = 'Ukjent'
}/**
* @export
* @enum {string}
*/
export enum BrukerFunksjonsnedsettelserEnum {
    BEVEGELSE = 'Bevegelse',
    HRSEL = 'Hørsel',
    KOGNISJON = 'Kognisjon'
}/**
* @export
* @enum {string}
*/
export enum BrukerSignaturEnum {
    FULLMAKT = 'Fullmakt',
    BRUKERBEKREFTELSE = 'Brukerbekreftelse'
}

export function BrukerFromJSON(json: any): Bruker {
    return BrukerFromJSONTyped(json, false);
}

export function BrukerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bruker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'etternavn': json['etternavn'],
        'fornavn': json['fornavn'],
        'fnummer': json['fnummer'],
        'telefonNummer': json['telefonNummer'],
        'adresse': !exists(json, 'adresse') ? undefined : json['adresse'],
        'postnummer': !exists(json, 'postnummer') ? undefined : json['postnummer'],
        'poststed': !exists(json, 'poststed') ? undefined : json['poststed'],
        'boform': json['boform'],
        'bruksarena': json['bruksarena'],
        'funksjonsnedsettelser': json['funksjonsnedsettelser'],
        'signatur': json['signatur'],
    };
}

export function BrukerToJSON(value?: Bruker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'etternavn': value.etternavn,
        'fornavn': value.fornavn,
        'fnummer': value.fnummer,
        'telefonNummer': value.telefonNummer,
        'adresse': value.adresse,
        'postnummer': value.postnummer,
        'poststed': value.poststed,
        'boform': value.boform,
        'bruksarena': value.bruksarena,
        'funksjonsnedsettelser': value.funksjonsnedsettelser,
        'signatur': value.signatur,
    };
}


