/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Bruker {
    'etternavn': string;
    'fornavn': string;
    'fnummer': string;
    'telefonNummer': string;
    'adresse'?: string;
    'postnummer'?: string;
    'poststed'?: string;
    'boform': BrukerBoformEnum;
    'bruksarena': BrukerBruksarenaEnum;
    'funksjonsnedsettelser': Array<BrukerFunksjonsnedsettelserEnum>;
    'signatur': BrukerSignaturEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "etternavn",
            "baseName": "etternavn",
            "type": "string",
            "format": ""
        },
        {
            "name": "fornavn",
            "baseName": "fornavn",
            "type": "string",
            "format": ""
        },
        {
            "name": "fnummer",
            "baseName": "fnummer",
            "type": "string",
            "format": ""
        },
        {
            "name": "telefonNummer",
            "baseName": "telefonNummer",
            "type": "string",
            "format": ""
        },
        {
            "name": "adresse",
            "baseName": "adresse",
            "type": "string",
            "format": ""
        },
        {
            "name": "postnummer",
            "baseName": "postnummer",
            "type": "string",
            "format": ""
        },
        {
            "name": "poststed",
            "baseName": "poststed",
            "type": "string",
            "format": ""
        },
        {
            "name": "boform",
            "baseName": "boform",
            "type": "BrukerBoformEnum",
            "format": ""
        },
        {
            "name": "bruksarena",
            "baseName": "bruksarena",
            "type": "BrukerBruksarenaEnum",
            "format": ""
        },
        {
            "name": "funksjonsnedsettelser",
            "baseName": "funksjonsnedsettelser",
            "type": "Array<BrukerFunksjonsnedsettelserEnum>",
            "format": ""
        },
        {
            "name": "signatur",
            "baseName": "signatur",
            "type": "BrukerSignaturEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Bruker.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type BrukerBoformEnum = "Hjemme" | "Institusjon" ;
export type BrukerBruksarenaEnum = "Dagligliv" | "Ukjent" ;
export type BrukerFunksjonsnedsettelserEnum = "Bevegelse" | "Hørsel" | "Kognisjon" ;
export type BrukerSignaturEnum = "Fullmakt" | "Brukerbekreftelse" ;

