/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Boform } from './Boform';
import { Bruksarena } from './Bruksarena';
import { Funksjonsnedsettelse } from './Funksjonsnedsettelse';
import { Kroppsmaal } from './Kroppsmaal';
import { SignaturType } from './SignaturType';
import { HttpFile } from '../http/http';

export class Bruker {
    'etternavn': string;
    'fornavn': string;
    'fnummer': string;
    'telefonNummer': string;
    'adresse'?: string;
    'postnummer'?: string;
    'poststed'?: string;
    'boform': Boform;
    'bruksarena': Bruksarena;
    'funksjonsnedsettelser': Array<Funksjonsnedsettelse>;
    'signatur': SignaturType;
    'kroppsmaal'?: Kroppsmaal;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "etternavn",
            "baseName": "etternavn",
            "type": "string",
            "format": ""
        },
        {
            "name": "fornavn",
            "baseName": "fornavn",
            "type": "string",
            "format": ""
        },
        {
            "name": "fnummer",
            "baseName": "fnummer",
            "type": "string",
            "format": ""
        },
        {
            "name": "telefonNummer",
            "baseName": "telefonNummer",
            "type": "string",
            "format": ""
        },
        {
            "name": "adresse",
            "baseName": "adresse",
            "type": "string",
            "format": ""
        },
        {
            "name": "postnummer",
            "baseName": "postnummer",
            "type": "string",
            "format": ""
        },
        {
            "name": "poststed",
            "baseName": "poststed",
            "type": "string",
            "format": ""
        },
        {
            "name": "boform",
            "baseName": "boform",
            "type": "Boform",
            "format": ""
        },
        {
            "name": "bruksarena",
            "baseName": "bruksarena",
            "type": "Bruksarena",
            "format": ""
        },
        {
            "name": "funksjonsnedsettelser",
            "baseName": "funksjonsnedsettelser",
            "type": "Array<Funksjonsnedsettelse>",
            "format": ""
        },
        {
            "name": "signatur",
            "baseName": "signatur",
            "type": "SignaturType",
            "format": ""
        },
        {
            "name": "kroppsmaal",
            "baseName": "kroppsmaal",
            "type": "Kroppsmaal",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Bruker.attributeTypeMap;
    }
    
    public constructor() {
    }
}

