/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HjelpemiddelVilkar } from './HjelpemiddelVilkar';
import { Tilbehor } from './Tilbehor';
import { HttpFile } from '../http/http';

export class Hjelpemiddel {
    'antall': number;
    'beskrivelse': string;
    'hjelpemiddelkategori'?: string;
    'hmsNr': string;
    'tilleggsinformasjon': string;
    'rangering'?: string;
    'utlevertFraHjelpemiddelsentralen': boolean;
    'vilkarliste'?: Array<HjelpemiddelVilkar>;
    'tilbehorListe'?: Array<Tilbehor>;
    'begrunnelse'?: string;
    'kanIkkeTilsvarande'?: boolean;
    'navn'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "antall",
            "baseName": "antall",
            "type": "number",
            "format": ""
        },
        {
            "name": "beskrivelse",
            "baseName": "beskrivelse",
            "type": "string",
            "format": ""
        },
        {
            "name": "hjelpemiddelkategori",
            "baseName": "hjelpemiddelkategori",
            "type": "string",
            "format": ""
        },
        {
            "name": "hmsNr",
            "baseName": "hmsNr",
            "type": "string",
            "format": ""
        },
        {
            "name": "tilleggsinformasjon",
            "baseName": "tilleggsinformasjon",
            "type": "string",
            "format": ""
        },
        {
            "name": "rangering",
            "baseName": "rangering",
            "type": "string",
            "format": ""
        },
        {
            "name": "utlevertFraHjelpemiddelsentralen",
            "baseName": "utlevertFraHjelpemiddelsentralen",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vilkarliste",
            "baseName": "vilkarliste",
            "type": "Array<HjelpemiddelVilkar>",
            "format": ""
        },
        {
            "name": "tilbehorListe",
            "baseName": "tilbehorListe",
            "type": "Array<Tilbehor>",
            "format": ""
        },
        {
            "name": "begrunnelse",
            "baseName": "begrunnelse",
            "type": "string",
            "format": ""
        },
        {
            "name": "kanIkkeTilsvarande",
            "baseName": "kanIkkeTilsvarande",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "navn",
            "baseName": "navn",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Hjelpemiddel.attributeTypeMap;
    }
    
    public constructor() {
    }
}

