/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class HjelpemiddelRullestolInfo {
    'skalBrukesIBil'?: boolean;
    'sitteputeValg'?: HjelpemiddelRullestolInfoSitteputeValgEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "skalBrukesIBil",
            "baseName": "skalBrukesIBil",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sitteputeValg",
            "baseName": "sitteputeValg",
            "type": "HjelpemiddelRullestolInfoSitteputeValgEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HjelpemiddelRullestolInfo.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type HjelpemiddelRullestolInfoSitteputeValgEnum = "StandardSittepute" | "LeggesTilSeparat" | "HarFraFor" ;

