/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class KontaktPerson {
    'navn'?: string;
    'telefon'?: string;
    'kontaktpersonType': KontaktPersonKontaktpersonTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "navn",
            "baseName": "navn",
            "type": "string",
            "format": ""
        },
        {
            "name": "telefon",
            "baseName": "telefon",
            "type": "string",
            "format": ""
        },
        {
            "name": "kontaktpersonType",
            "baseName": "kontaktpersonType",
            "type": "KontaktPersonKontaktpersonTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KontaktPerson.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type KontaktPersonKontaktpersonTypeEnum = "HJELPEMIDDELBRUKER" | "HJELPEMIDDELFORMIDLER" | "ANNEN_KONTAKTPERSON" | "INGEN_KONTAKTPERSON" ;

