/* tslint:disable */
/* eslint-disable */
/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KontaktPerson
 */
export interface KontaktPerson {
    /**
     * 
     * @type {string}
     * @memberof KontaktPerson
     */
    navn?: string;
    /**
     * 
     * @type {string}
     * @memberof KontaktPerson
     */
    telefon?: string;
    /**
     * 
     * @type {string}
     * @memberof KontaktPerson
     */
    kontaktpersonType: KontaktPersonKontaktpersonTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum KontaktPersonKontaktpersonTypeEnum {
    HJELPEMIDDELBRUKER = 'HJELPEMIDDELBRUKER',
    HJELPEMIDDELFORMIDLER = 'HJELPEMIDDELFORMIDLER',
    ANNEN_KONTAKTPERSON = 'ANNEN_KONTAKTPERSON',
    INGEN_KONTAKTPERSON = 'INGEN_KONTAKTPERSON'
}

export function KontaktPersonFromJSON(json: any): KontaktPerson {
    return KontaktPersonFromJSONTyped(json, false);
}

export function KontaktPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): KontaktPerson {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'navn': !exists(json, 'navn') ? undefined : json['navn'],
        'telefon': !exists(json, 'telefon') ? undefined : json['telefon'],
        'kontaktpersonType': json['kontaktpersonType'],
    };
}

export function KontaktPersonToJSON(value?: KontaktPerson | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'navn': value.navn,
        'telefon': value.telefon,
        'kontaktpersonType': value.kontaktpersonType,
    };
}


