/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Kroppsmaal {
    'setebredde'?: number;
    'laarlengde'?: number;
    'legglengde'?: number;
    'hoyde'?: number;
    'kroppsvekt'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "setebredde",
            "baseName": "setebredde",
            "type": "number",
            "format": ""
        },
        {
            "name": "laarlengde",
            "baseName": "laarlengde",
            "type": "number",
            "format": ""
        },
        {
            "name": "legglengde",
            "baseName": "legglengde",
            "type": "number",
            "format": ""
        },
        {
            "name": "hoyde",
            "baseName": "hoyde",
            "type": "number",
            "format": ""
        },
        {
            "name": "kroppsvekt",
            "baseName": "kroppsvekt",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Kroppsmaal.attributeTypeMap;
    }
    
    public constructor() {
    }
}

