/* tslint:disable */
/* eslint-disable */
/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    KontaktPerson,
    KontaktPersonFromJSON,
    KontaktPersonFromJSONTyped,
    KontaktPersonToJSON,
} from './';

/**
 * 
 * @export
 * @interface Levering
 */
export interface Levering {
    /**
     * 
     * @type {KontaktPerson}
     * @memberof Levering
     */
    kontaktPerson: KontaktPerson;
    /**
     * 
     * @type {string}
     * @memberof Levering
     */
    leveringsmaate: LeveringLeveringsmaateEnum;
    /**
     * 
     * @type {string}
     * @memberof Levering
     */
    adresse?: string;
    /**
     * 
     * @type {string}
     * @memberof Levering
     */
    merknad?: string;
}

/**
* @export
* @enum {string}
*/
export enum LeveringLeveringsmaateEnum {
    FOLKEREGISTRERT_ADRESSE = 'FOLKEREGISTRERT_ADRESSE',
    ANNEN_ADRESSE = 'ANNEN_ADRESSE',
    HJELPEMIDDELSENTRAL = 'HJELPEMIDDELSENTRAL',
    ALLEREDE_LEVERT = 'ALLEREDE_LEVERT'
}

export function LeveringFromJSON(json: any): Levering {
    return LeveringFromJSONTyped(json, false);
}

export function LeveringFromJSONTyped(json: any, ignoreDiscriminator: boolean): Levering {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kontaktPerson': KontaktPersonFromJSON(json['kontaktPerson']),
        'leveringsmaate': json['leveringsmaate'],
        'adresse': !exists(json, 'adresse') ? undefined : json['adresse'],
        'merknad': !exists(json, 'merknad') ? undefined : json['merknad'],
    };
}

export function LeveringToJSON(value?: Levering | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kontaktPerson': KontaktPersonToJSON(value.kontaktPerson),
        'leveringsmaate': value.leveringsmaate,
        'adresse': value.adresse,
        'merknad': value.merknad,
    };
}


