/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KontaktPerson } from './KontaktPerson';
import { Leveringsmaate } from './Leveringsmaate';
import { HttpFile } from '../http/http';

export class Levering {
    'kontaktPerson': KontaktPerson;
    'leveringsmaate': Leveringsmaate;
    'adresse'?: string;
    'merknad'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "kontaktPerson",
            "baseName": "kontaktPerson",
            "type": "KontaktPerson",
            "format": ""
        },
        {
            "name": "leveringsmaate",
            "baseName": "leveringsmaate",
            "type": "Leveringsmaate",
            "format": ""
        },
        {
            "name": "adresse",
            "baseName": "adresse",
            "type": "string",
            "format": ""
        },
        {
            "name": "merknad",
            "baseName": "merknad",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Levering.attributeTypeMap;
    }
    
    public constructor() {
    }
}

