/* tslint:disable */
/* eslint-disable */
/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Oppfolgingsansvarlig
 */
export interface Oppfolgingsansvarlig {
    /**
     * 
     * @type {string}
     * @memberof Oppfolgingsansvarlig
     */
    navn: string;
    /**
     * 
     * @type {string}
     * @memberof Oppfolgingsansvarlig
     */
    arbeidssted: string;
    /**
     * 
     * @type {string}
     * @memberof Oppfolgingsansvarlig
     */
    stilling: string;
    /**
     * 
     * @type {string}
     * @memberof Oppfolgingsansvarlig
     */
    telefon: string;
    /**
     * 
     * @type {string}
     * @memberof Oppfolgingsansvarlig
     */
    ansvarFor: string;
}

export function OppfolgingsansvarligFromJSON(json: any): Oppfolgingsansvarlig {
    return OppfolgingsansvarligFromJSONTyped(json, false);
}

export function OppfolgingsansvarligFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oppfolgingsansvarlig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'navn': json['navn'],
        'arbeidssted': json['arbeidssted'],
        'stilling': json['stilling'],
        'telefon': json['telefon'],
        'ansvarFor': json['ansvarFor'],
    };
}

export function OppfolgingsansvarligToJSON(value?: Oppfolgingsansvarlig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'navn': value.navn,
        'arbeidssted': value.arbeidssted,
        'stilling': value.stilling,
        'telefon': value.telefon,
        'ansvarFor': value.ansvarFor,
    };
}


