/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Bruker } from './Bruker';
import { Formidler } from './Formidler';
import { Hjelpemiddel } from './Hjelpemiddel';
import { Levering } from './Levering';
import { Oppfolgingsansvarlig } from './Oppfolgingsansvarlig';
import { HttpFile } from '../http/http';

export class Soknadsdata {
    'bruker': Bruker;
    'formidler': Formidler;
    'hjelpemidler': Array<Hjelpemiddel>;
    'hjelpemiddelTotalAntall': number;
    'oppfolgingsansvarlig': Oppfolgingsansvarlig;
    'levering': Levering;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bruker",
            "baseName": "bruker",
            "type": "Bruker",
            "format": ""
        },
        {
            "name": "formidler",
            "baseName": "formidler",
            "type": "Formidler",
            "format": ""
        },
        {
            "name": "hjelpemidler",
            "baseName": "hjelpemidler",
            "type": "Array<Hjelpemiddel>",
            "format": ""
        },
        {
            "name": "hjelpemiddelTotalAntall",
            "baseName": "hjelpemiddelTotalAntall",
            "type": "number",
            "format": ""
        },
        {
            "name": "oppfolgingsansvarlig",
            "baseName": "oppfolgingsansvarlig",
            "type": "Oppfolgingsansvarlig",
            "format": ""
        },
        {
            "name": "levering",
            "baseName": "levering",
            "type": "Levering",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Soknadsdata.attributeTypeMap;
    }
    
    public constructor() {
    }
}

