/* tslint:disable */
/* eslint-disable */
/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Bruker,
    BrukerFromJSON,
    BrukerFromJSONTyped,
    BrukerToJSON,
    Formidler,
    FormidlerFromJSON,
    FormidlerFromJSONTyped,
    FormidlerToJSON,
    Hjelpemiddel,
    HjelpemiddelFromJSON,
    HjelpemiddelFromJSONTyped,
    HjelpemiddelToJSON,
    Levering,
    LeveringFromJSON,
    LeveringFromJSONTyped,
    LeveringToJSON,
    Oppfolgingsansvarlig,
    OppfolgingsansvarligFromJSON,
    OppfolgingsansvarligFromJSONTyped,
    OppfolgingsansvarligToJSON,
} from './';

/**
 * 
 * @export
 * @interface Soknadsdata
 */
export interface Soknadsdata {
    /**
     * 
     * @type {Bruker}
     * @memberof Soknadsdata
     */
    bruker: Bruker;
    /**
     * 
     * @type {Formidler}
     * @memberof Soknadsdata
     */
    formidler: Formidler;
    /**
     * 
     * @type {Array<Hjelpemiddel>}
     * @memberof Soknadsdata
     */
    hjelpemidler: Array<Hjelpemiddel>;
    /**
     * 
     * @type {number}
     * @memberof Soknadsdata
     */
    hjelpemiddelTotalAntall: number;
    /**
     * 
     * @type {Oppfolgingsansvarlig}
     * @memberof Soknadsdata
     */
    oppfolgingsansvarlig: Oppfolgingsansvarlig;
    /**
     * 
     * @type {Levering}
     * @memberof Soknadsdata
     */
    levering: Levering;
}

export function SoknadsdataFromJSON(json: any): Soknadsdata {
    return SoknadsdataFromJSONTyped(json, false);
}

export function SoknadsdataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Soknadsdata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bruker': BrukerFromJSON(json['bruker']),
        'formidler': FormidlerFromJSON(json['formidler']),
        'hjelpemidler': ((json['hjelpemidler'] as Array<any>).map(HjelpemiddelFromJSON)),
        'hjelpemiddelTotalAntall': json['hjelpemiddelTotalAntall'],
        'oppfolgingsansvarlig': OppfolgingsansvarligFromJSON(json['oppfolgingsansvarlig']),
        'levering': LeveringFromJSON(json['levering']),
    };
}

export function SoknadsdataToJSON(value?: Soknadsdata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bruker': BrukerToJSON(value.bruker),
        'formidler': FormidlerToJSON(value.formidler),
        'hjelpemidler': ((value.hjelpemidler as Array<any>).map(HjelpemiddelToJSON)),
        'hjelpemiddelTotalAntall': value.hjelpemiddelTotalAntall,
        'oppfolgingsansvarlig': OppfolgingsansvarligToJSON(value.oppfolgingsansvarlig),
        'levering': LeveringToJSON(value.levering),
    };
}


