/* tslint:disable */
/* eslint-disable */
/**
 * Hjelpemiddelsøknad model spec
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tilbehor
 */
export interface Tilbehor {
    /**
     * 
     * @type {string}
     * @memberof Tilbehor
     */
    hmsnr: string;
    /**
     * 
     * @type {number}
     * @memberof Tilbehor
     */
    antall: number;
    /**
     * 
     * @type {string}
     * @memberof Tilbehor
     */
    navn: string;
}

export function TilbehorFromJSON(json: any): Tilbehor {
    return TilbehorFromJSONTyped(json, false);
}

export function TilbehorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tilbehor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hmsnr': json['hmsnr'],
        'antall': json['antall'],
        'navn': json['navn'],
    };
}

export function TilbehorToJSON(value?: Tilbehor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hmsnr': value.hmsnr,
        'antall': value.antall,
        'navn': value.navn,
    };
}


